# Generated by Django 6.0.3 on 2026-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='farmer',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
