# Generated by Django 6.0.3 on 2026-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_farmer_phone_farmer_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(default='Wheat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_size',
            field=models.CharField(default='1 Acre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='temperature',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
