# Generated by Django 6.0.3 on 2026-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='temperature',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
