# Generated by Django 6.0.3 on 2026-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
